/* =====================================================
   TIME ECHO PLATFORMER v3 — config.js
   Global constants, themes, pets, outfits, achievements
   ===================================================== */
window.TEP = window.TEP || {};

TEP.CONFIG = {
  CANVAS_W: 960,
  CANVAS_H: 520,
  GRAVITY: 0.55,
  FRICTION: 0.78,
  MAX_RECORD_FRAMES: 360,
  MAX_ECHOES: 3,
  TRAIL_LEN: 14,

  // ── Death messages by cause ──────────────────────
  DEATH_MESSAGES: {
    spike: [
      "The spikes were clearly decorative. Spoiler: they weren't.",
      "You hugged a spike. It did not hug back.",
      "Sir, those are pointy. Very, very pointy.",
      "You donated your HP to the spike collection.",
      "Spike: 1. You: permanently horizontal.",
       "Congratulations, you invented human kebab.",
    "You mistook spikes for a mattress. Bold choice.",
    "Spikes don’t do hugs. They do skewers.",
    "You just unlocked the ‘Shish Kebab’ achievement.",
    "The spikes are now wearing you as fashion.",
    ],
    lava: [
      "The lava says hi. And also goodbye.",
      "Hot take: don't stand in molten rock.",
      "You speedran into a lava bath. Unsolicited.",
      "Turns out lava is hot. Revolutionary discovery.",
      "Your echo is filing a heat complaint.",
       "You jumped into soup. Soup was lava.",
    "Molten rock: not a jacuzzi, champ.",
    "You speedran into a cremation service.",
    "Breaking news: lava is still hot.",
    "Your echo is roasting marshmallows on your remains.",
    ],
    enemy: [
      "The enemy had beef with you specifically.",
      "The Wisp just wanted a hug. You gave it a death.",
      "The Sentinel rewound itself directly into your face.",
      "The Paradox Beast took notes for next time.",
      "You were outplayed by something that doesn't exist yet.",
       "You lost to something coded in 12 lines.",
    "The Wisp corrupted your dignity too.",
    "Chrono Sentinel rewound your skill back to zero.",
    "Paradox Beast copied your bad decisions perfectly.",
    "You got clapped by a tutorial enemy.",
    ],
    fall: [
      "Gravity called. You answered enthusiastically.",
      "You speedran the wrong direction. Downward.",
      "The void wasn't empty — it was waiting.",
      "Fell off the map. At least you found the floor.",
      "Your echo watched you fall and said nothing.",
       "Gravity just rage‑quit you from existence.",
    "You discovered the fast‑travel option: straight down.",
    "The void was lonely. You volunteered.",
    "Floor speedrun complete. PB: instant.",
    "Your echo watched you plummet and filed for custody.",
   
    ],
    generic: [
      "Paradox detected: you died before you could die.",
      "The universe said no.",
      "Physics: 1 — You: 0.",
      "You were doing so well. (You weren't.)",
      "Even your echo facepalmed.",
      "Skill issue detected. Initiating restart.",
      "Your mom's watching. She's concerned.",
      "Reality TV moment. Not a good one.",
      "You became a cautionary tale.",
      "Time echoes cannot save you from yourself.",
      "404: Player skill not found.",
      "Even the background was embarrassed for you.",
      "Sir, this is a puzzle game. Please puzzle better.",
      "The past called. It wants its mistakes back.",
      "The paradox beast was literally just standing there.",
      "You tried. The level disagreed.",
      "Press F to pay respects. The level won't.",
       "Skill issue so severe it echoed across timelines.",
    "You died in 4K Ultra HD embarrassment.",
    "Physics called. Said you’re unemployed.",
    "Even the pause menu is disappointed.",
    "Your echoes are unionizing against your gameplay.",
    "404: Gamer instincts not found.",
    "You became a meme in another universe.",
    "The background scenery unfollowed you.",
    "Puzzle game. You brought FPS aim. Wrong genre.",
    "Your past self regrets being associated with you.",
    ],
    laser: [
      "You walked into a laser like it owed you money.",
      "Red means stop. You did not stop.",
      "The laser was decorative. (It was not.)",
       "You walked into a rave light and got deleted.",
    "Red means stop. You speedran into oblivion.",
    "Laser beams are not collectibles, my guy.",
    ],
    wisp_corrupt: [
      "The Wisp corrupted your soul. And also your echo.",
      "Your recording is now modern art. Unrecoverable.",
      "Static noise intensifies. So does your pain.",
       "The Wisp corrupted your save file *and* your pride.",
    "Your echo is now abstract art. You are not.",
    "Static noise: louder than your skill level.",
    ],
  },

  // ── Biome themes (15 total) ────────────────────────
  THEMES: {
    cave: {
      name: 'Crystal Cave', isNight: false,
      skyTop:'#060212', skyBot:'#1a0a2e',
      far:'#0d0520', mid:'#1a0a38', near:'#2d1155',
      ground:'#3d2b0a', platformTop:'#7a5a10', platformSide:'#4a3508', platformLight:'#c49a20',
      fogColor:'rgba(80,20,160,0.06)', hasLava:true,
      ambience:'rgba(60,10,120,0.05)',
    },
    neon_city: {
      name: 'Neon City', isNight: false,
      skyTop:'#000510', skyBot:'#060d22',
      far:'#050510', mid:'#080820', near:'#0d0d2e',
      ground:'#0a0a20', platformTop:'#1a0a5a', platformSide:'#0d0540', platformLight:'#6030ff',
      fogColor:'rgba(100,40,255,0.1)', hasLava:false,
      ambience:'rgba(80,20,200,0.08)',
    },
    sunset_ruins: {
      name: 'Sunset Ruins', isNight: false,
      skyTop:'#1a0533', skyBot:'#e84800',
      far:'#7b1d3a', mid:'#5a1226', near:'#3d0d1a',
      ground:'#2e6b14', platformTop:'#5a8c1e', platformSide:'#3a5c10', platformLight:'#90e840',
      fogColor:'rgba(255,100,40,0.07)', hasLava:false,
      ambience:'rgba(255,80,20,0.04)',
    },
    crystal_sky: {
      name: 'Crystal Sky', isNight: false,
      skyTop:'#030c1a', skyBot:'#0a2555',
      far:'#0a1a3a', mid:'#0d2855', near:'#0f3070',
      ground:'#0a3355', platformTop:'#1a7aaa', platformSide:'#0f4a70', platformLight:'#55d4ff',
      fogColor:'rgba(40,180,255,0.08)', hasLava:false,
      ambience:'rgba(10,100,200,0.06)',
    },
    haunted_forest: {
      name: 'Haunted Forest', isNight: false,
      skyTop:'#050d05', skyBot:'#0d1f0d',
      far:'#0a150a', mid:'#0f2010', near:'#142814',
      ground:'#1a3d0a', platformTop:'#2a6014', platformSide:'#1a3d0a', platformLight:'#44cc22',
      fogColor:'rgba(40,180,40,0.06)', hasLava:false,
      ambience:'rgba(20,100,20,0.06)',
    },
    frozen_peaks: {
      name: 'Frozen Peaks', isNight: false,
      skyTop:'#030d1a', skyBot:'#0a2a40',
      far:'#0a1e35', mid:'#0f2e4a', near:'#14385a',
      ground:'#7ad4e8', platformTop:'#9ae4f5', platformSide:'#5ab0cc', platformLight:'#ccf5ff',
      fogColor:'rgba(140,220,255,0.08)', hasLava:false,
      ambience:null,
    },
    lava_core: {
      name: 'Lava Core', isNight: false,
      skyTop:'#0a0000', skyBot:'#2a0500',
      far:'#3a0800', mid:'#501000', near:'#651500',
      ground:'#4a1500', platformTop:'#6b2200', platformSide:'#401400', platformLight:'#dd3300',
      fogColor:'rgba(255,60,0,0.12)', hasLava:true,
      ambience:'rgba(255,40,0,0.06)',
    },
    temple_gold: {
      name: 'Golden Temple', isNight: false,
      skyTop:'#0a0a05', skyBot:'#2a2005',
      far:'#1a1505', mid:'#2e2608', near:'#403510',
      ground:'#5c4a18', platformTop:'#a08030', platformSide:'#6b5520', platformLight:'#d4aa55',
      fogColor:'rgba(200,160,40,0.07)', hasLava:false,
      ambience:'rgba(200,150,20,0.04)',
    },
    paradox_void: {
      name: 'Paradox Void', isNight: false,
      skyTop:'#050010', skyBot:'#100520',
      far:'#0a052a', mid:'#150a40', near:'#200f55',
      ground:'#1a0a40', platformTop:'#6a00cc', platformSide:'#400080', platformLight:'#aa44ff',
      fogColor:'rgba(180,0,255,0.15)', hasLava:false,
      ambience:'rgba(120,0,200,0.10)',
    },
    sky_islands: {
      name: 'Sky Islands', isNight: false,
      skyTop:'#1a4aaa', skyBot:'#5ab0f0',
      far:'#3a7acc', mid:'#5a9ae0', near:'#aaccee',
      ground:'#c8e8ff', platformTop:'#e8f4ff', platformSide:'#b0d0f0', platformLight:'#ffffff',
      fogColor:'rgba(200,230,255,0.12)', hasLava:false,
      ambience:null,
    },
    deep_ocean: {
      name: 'Deep Ocean', isNight: false,
      skyTop:'#000814', skyBot:'#001a30',
      far:'#001028', mid:'#001838', near:'#002045',
      ground:'#003060', platformTop:'#004080', platformSide:'#002855', platformLight:'#0099cc',
      fogColor:'rgba(0,150,255,0.08)', hasLava:false,
      ambience:'rgba(0,80,150,0.08)',
    },
    desert_night: {
      name: 'Desert Night', isNight: false,
      skyTop:'#05030a', skyBot:'#0d0820',
      far:'#0a0618', mid:'#120c25', near:'#1a1235',
      ground:'#8a6a20', platformTop:'#aa8828', platformSide:'#7a5818', platformLight:'#ddaa44',
      fogColor:'rgba(200,150,50,0.06)', hasLava:false,
      ambience:'rgba(150,100,20,0.04)',
    },
    blood_moon: {
      name: 'Blood Moon', isNight: false,
      skyTop:'#0a0005', skyBot:'#300010',
      far:'#1a0010', mid:'#280018', near:'#380020',
      ground:'#2a0010', platformTop:'#550020', platformSide:'#3a0018', platformLight:'#cc0040',
      fogColor:'rgba(200,0,60,0.12)', hasLava:false,
      ambience:'rgba(180,0,40,0.08)',
    },
    time_rift: {
      name: 'Time Rift', isNight: false,
      skyTop:'#000a0a', skyBot:'#001a20',
      far:'#001520', mid:'#002030', near:'#002840',
      ground:'#003344', platformTop:'#005566', platformSide:'#003344', platformLight:'#00eecc',
      fogColor:'rgba(0,220,200,0.08)', hasLava:false,
      ambience:'rgba(0,180,160,0.06)',
    },
    ember_ruins: {
      name: 'Ember Ruins', isNight: false,
      skyTop:'#100500', skyBot:'#4a1500',
      far:'#3a1000', mid:'#501800', near:'#6a2200',
      ground:'#5a3a10', platformTop:'#8a5a18', platformSide:'#5a3a10', platformLight:'#cc8833',
      fogColor:'rgba(255,120,40,0.10)', hasLava:true,
      ambience:'rgba(200,80,20,0.06)',
    },
  },

  // ── Pets (12 total, with more personality) ─────────
  PETS: [
    {
      id:'chrono_cat', name:'Chrono Cat', desc:'+1s record time. Purrs near echoes.', cost:150,
      emoji:'🐱', color:'#f5a623', perk:'recordTime', value:60,
      story:'Found frozen in a time loop. Now follows you, deeply confused but loyal.',
    },
    {
      id:'paradox_pup', name:'Paradox Pup', desc:'Barks near switches. +10% coin magnet.', cost:200,
      emoji:'🐶', color:'#a78bfa', perk:'switchAlert', value:1,
      story:'A dog that exists in two timelines simultaneously. Very good boy. Both of him.',
    },
    {
      id:'wisp_bird', name:'Wisp Bird', desc:'Perches on switches. Glows cyan.', cost:300,
      emoji:'🐦', color:'#7efff5', perk:'switchPerch', value:30,
      story:'Born from a corrupted echo. Now hunts wisps for sport. It\'s complicated.',
    },
    {
      id:'copper_golem', name:'Copper Golem', desc:'Walks beside you. Presses ONE button per level.', cost:500,
      emoji:'🤖', color:'#b87333', perk:'buttonPress', value:1,
      story:'Built to help. Helps occasionally. Still learning. Very eager. Very clunky.',
    },
    {
      id:'phantom_fox', name:'Phantom Fox', desc:'Warns of enemies nearby. Shares your trail.', cost:400,
      emoji:'🦊', color:'#ff6b35', perk:'enemyAlert', value:1,
      story:'A ghost of a fox who was outrun by time. Now it runs beside you, just in case.',
    },
    {
      id:'star_jellyfish', name:'Star Jelly', desc:'Slows fall 15%. Glows in dark levels.', cost:350,
      emoji:'🪼', color:'#cc88ff', perk:'floatFall', value:0.85,
      story:'Fell from another dimension entirely. Glows beautifully. Doesn\'t know why.',
    },
    {
      id:'time_ferret', name:'Time Ferret', desc:'Occasionally steals coins from enemies.', cost:250,
      emoji:'🦦', color:'#8B6914', perk:'coinSteal', value:1,
      story:'Steals things from the future. Mostly coins. Sometimes regrets.',
    },
    {
      id:'echo_sprite', name:'Echo Sprite', desc:'Creates a 4th echo slot temporarily.', cost:600,
      emoji:'✨', color:'#88ffaa', perk:'extraEcho', value:1,
      story:'A fragment of a lost echo that never found its player. Now it\'s found you.',
    },
    {
      id:'shadow_wolf', name:'Shadow Wolf', desc:'Scares enemies briefly on echo spawn.', cost:450,
      emoji:'🐺', color:'#6633cc', perk:'fearAura', value:1,
      story:'Prowls the echo dimension. Hates paradoxes. Somehow hates you less.',
    },
    {
      id:'time_turtle', name:'Time Turtle', desc:'Blocks one hit from enemies. Once per level.', cost:550,
      emoji:'🐢', color:'#44aa66', perk:'shield', value:1,
      story:'Moves slowly. Has seen every timeline. Chooses to protect you specifically.',
    },
    {
      id:'neon_butterfly', name:'Neon Butterfly', desc:'+15% score multiplier.', cost:300,
      emoji:'🦋', color:'#ff44cc', perk:'scoreBoost', value:1.15,
      story:'Made of pure light from a collapsed dimension. Absolutely stunning. Very helpful.',
    },
    {
      id:'chrono_crab', name:'Chrono Crab', desc:'Holds pressure plates with claws. So useful.', cost:480,
      emoji:'🦀', color:'#ff4400', perk:'plateHold', value:1,
      story:'Sideways through time. Stubborn as the timeline itself. Will not move off plates.',
    },
  ],

  // ── Outfits (15 total) ────────────────────────────
  OUTFITS: [
    { id:'default',    name:'Echo Suit',       cost:0,   color:'#00d4ff', echoHue:190, glow:'#00d4ff', desc:'Standard issue. Still cool.' },
    { id:'cyberpunk',  name:'Cyberpunk',        cost:100, color:'#ff00dd', echoHue:300, glow:'#ff00dd', desc:'Neon and attitude.' },
    { id:'retro',      name:'Retro Pixel',      cost:150, color:'#ff6b35', echoHue:25,  glow:'#ff8855', desc:'Classic never dies.' },
    { id:'shadow',     name:'Shadow Walker',    cost:200, color:'#9966cc', echoHue:280, glow:'#aa44ff', desc:'You are the darkness.' },
    { id:'forest',     name:'Forest Cloak',     cost:250, color:'#2ecc71', echoHue:130, glow:'#44ff88', desc:'One with the trees.' },
    { id:'space',      name:'Void Suit',         cost:350, color:'#9b59b6', echoHue:285, glow:'#cc66ff', desc:'Stars envy you.' },
    { id:'golden',     name:'Golden Echo',       cost:400, color:'#ffd700', echoHue:50,  glow:'#ffee44', desc:'You KNOW you look good.' },
    { id:'crimson',    name:'Crimson Paradox',   cost:450, color:'#ff3355', echoHue:350, glow:'#ff4466', desc:'Paradox never looked this good.' },
    { id:'ice',        name:'Frozen Apex',       cost:300, color:'#88eeff', echoHue:195, glow:'#aaffff', desc:'Ice cold execution.' },
    { id:'lava',       name:'Magma Walker',      cost:380, color:'#ff6600', echoHue:22,  glow:'#ff8800', desc:'Heat doesn\'t bother you anymore.' },
    { id:'phantom',    name:'Phantom Weave',     cost:500, color:'#aaddff', echoHue:210, glow:'#cceeff', desc:'Barely there. Fully deadly.' },
    { id:'aurora',     name:'Aurora',            cost:550, color:'#88ffcc', echoHue:160, glow:'#aaffdd', desc:'Every level is a light show now.' },
    { id:'obsidian',   name:'Obsidian Knight',   cost:480, color:'#334455', echoHue:220, glow:'#5577aa', desc:'Ancient. Sturdy. Mysterious.' },
    { id:'nebula',     name:'Nebula Drift',      cost:600, color:'#cc44ff', echoHue:280, glow:'#ee66ff', desc:'You are the galaxy.' },
    { id:'glitch',     name:'Glitch Core',       cost:350, color:'#ff0088', echoHue:330, glow:'#ff44aa', desc:'Error. Error. Looking great.' },
  ],

  // ── Achievements (20 total) ────────────────────────
  ACHIEVEMENTS: [
    { id:'first_echo',     name:'Echo Chamber',     desc:'Spawn your first echo',           coins:10  },
    { id:'squad',          name:'Time Squad',        desc:'3 echoes active at once',         coins:25  },
    { id:'level5',         name:'Time Traveler',     desc:'Reach Level 5',                   coins:50  },
    { id:'level10',        name:'Paradox Master',    desc:'Reach Level 10',                  coins:100 },
    { id:'level20',        name:'Time Lord',         desc:'Complete all 20 levels',          coins:250 },
    { id:'speedrun',       name:'Blip in Time',      desc:'Complete any level under 20s',    coins:75  },
    { id:'fashion',        name:'Fashionably Late',  desc:'Clear a level in a rare outfit',  coins:50  },
    { id:'endless100',     name:'Infinity Runner',   desc:'Score 100+ in endless mode',      coins:60  },
    { id:'no_echo',        name:'Solo Paradox',      desc:'Beat level 3 with 0 echoes',      coins:80  },
    { id:'pet_owner',      name:'Best Friends',      desc:'Equip a pet',                     coins:20  },
    { id:'collector',      name:'Coin Hoarder',      desc:'Collect 500 coins lifetime',      coins:40  },
    { id:'night_owl',      name:'Night Owl',         desc:'Complete a night level',          coins:30  },
    { id:'no_death_lvl1',  name:'Flawless Echo',     desc:'Complete level 1 without dying',  coins:45  },
    { id:'all_coins',      name:'Completionist',     desc:'Collect all coins in any level',  coins:60  },
    { id:'enemy_echo',     name:'Echo Bait',         desc:'Let a Paradox Beast copy you 3x', coins:35  },
    { id:'daily_player',   name:'Time Keeper',       desc:'Complete a daily challenge',      coins:50  },
    { id:'shopaholic',     name:'Big Spender',       desc:'Spend 500 coins in the shop',     coins:40  },
    { id:'echo_master',    name:'Echo Master',       desc:'Use 50 echoes total',             coins:75  },
    { id:'friend',         name:'Better Together',   desc:'Add your first friend',           coins:30  },
    { id:'all_themes',     name:'World Walker',      desc:'Play in 5 different themes',      coins:80  },
  ],

  // ── Echo colors ────────────────────────────────────
  ECHO_COLORS: ['#7efff5','#ff7ef4','#7eff8b','#ffdd7e','#ff9966','#c07eff','#7eb3ff','#ffb37e','#ff6666','#aaffcc'],
};
